#
# THIS IS A GENERATED FILE
#
# Do not change!  Changing this file implies a protocol change!
#

import
  x

const
  XA_PRIMARY* = Atom(1)
  XA_SECONDARY* = Atom(2)
  XA_ARC* = Atom(3)
  XA_ATOM* = Atom(4)
  XA_BITMAP* = Atom(5)
  XA_CARDINAL* = Atom(6)
  XA_COLORMAP* = Atom(7)
  XA_CURSOR* = Atom(8)
  XA_CUT_BUFFER0* = Atom(9)
  XA_CUT_BUFFER1* = Atom(10)
  XA_CUT_BUFFER2* = Atom(11)
  XA_CUT_BUFFER3* = Atom(12)
  XA_CUT_BUFFER4* = Atom(13)
  XA_CUT_BUFFER5* = Atom(14)
  XA_CUT_BUFFER6* = Atom(15)
  XA_CUT_BUFFER7* = Atom(16)
  XA_DRAWABLE* = Atom(17)
  XA_FONT* = Atom(18)
  XA_INTEGER* = Atom(19)
  XA_PIXMAP* = Atom(20)
  XA_POINT* = Atom(21)
  XA_RECTANGLE* = Atom(22)
  XA_RESOURCE_MANAGER* = Atom(23)
  XA_RGB_COLOR_MAP* = Atom(24)
  XA_RGB_BEST_MAP* = Atom(25)
  XA_RGB_BLUE_MAP* = Atom(26)
  XA_RGB_DEFAULT_MAP* = Atom(27)
  XA_RGB_GRAY_MAP* = Atom(28)
  XA_RGB_GREEN_MAP* = Atom(29)
  XA_RGB_RED_MAP* = Atom(30)
  XA_STRING* = Atom(31)
  XA_VISUALID* = Atom(32)
  XA_WINDOW* = Atom(33)
  XA_WM_COMMAND* = Atom(34)
  XA_WM_HINTS* = Atom(35)
  XA_WM_CLIENT_MACHINE* = Atom(36)
  XA_WM_ICON_NAME* = Atom(37)
  XA_WM_ICON_SIZE* = Atom(38)
  XA_WM_NAME* = Atom(39)
  XA_WM_NORMAL_HINTS* = Atom(40)
  XA_WM_SIZE_HINTS* = Atom(41)
  XA_WM_ZOOM_HINTS* = Atom(42)
  XA_MIN_SPACE* = Atom(43)
  XA_NORM_SPACE* = Atom(44)
  XA_MAX_SPACE* = Atom(45)
  XA_END_SPACE* = Atom(46)
  XA_SUPERSCRIPT_X* = Atom(47)
  XA_SUPERSCRIPT_Y* = Atom(48)
  XA_SUBSCRIPT_X* = Atom(49)
  XA_SUBSCRIPT_Y* = Atom(50)
  XA_UNDERLINE_POSITION* = Atom(51)
  XA_UNDERLINE_THICKNESS* = Atom(52)
  XA_STRIKEOUT_ASCENT* = Atom(53)
  XA_STRIKEOUT_DESCENT* = Atom(54)
  XA_ITALIC_ANGLE* = Atom(55)
  XA_X_HEIGHT* = Atom(56)
  XA_QUAD_WIDTH* = Atom(57)
  XA_WEIGHT* = Atom(58)
  XA_POINT_SIZE* = Atom(59)
  XA_RESOLUTION* = Atom(60)
  XA_COPYRIGHT* = Atom(61)
  XA_NOTICE* = Atom(62)
  XA_FONT_NAME* = Atom(63)
  XA_FAMILY_NAME* = Atom(64)
  XA_FULL_NAME* = Atom(65)
  XA_CAP_HEIGHT* = Atom(66)
  XA_WM_CLASS* = Atom(67)
  XA_WM_TRANSIENT_FOR* = Atom(68)
  XA_LAST_PREDEFINED* = Atom(68)

# implementation
